[project]
name = "api-de-tarefas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.6",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.15.0",
    "sqlalchemy>=2.1.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.9",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]